apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-webapp
