replicaCount: 10

image:
  repository: ardutgamer/webapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort: 30000

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
